# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /sto2/sw/tools/cmake/3.14.1/bin/cmake

# The command to remove a file.
RM = /sto2/sw/tools/cmake/3.14.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jm17923/acrc_internship/summer20/iqtree/IQ-TREE

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jm17923/acrc_internship/summer20/iqtree/IQ-TREE

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/sto2/sw/tools/cmake/3.14.1/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/sto2/sw/tools/cmake/3.14.1/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/sto2/sw/tools/cmake/3.14.1/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/sto2/sw/tools/cmake/3.14.1/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/sto2/sw/tools/cmake/3.14.1/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/sto2/sw/tools/cmake/3.14.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/sto2/sw/tools/cmake/3.14.1/bin/cpack --config ./CPackSourceConfig.cmake /home/jm17923/acrc_internship/summer20/iqtree/IQ-TREE/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/sto2/sw/tools/cmake/3.14.1/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/sto2/sw/tools/cmake/3.14.1/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/sto2/sw/tools/cmake/3.14.1/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jm17923/acrc_internship/summer20/iqtree/IQ-TREE/CMakeFiles /home/jm17923/acrc_internship/summer20/iqtree/IQ-TREE/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jm17923/acrc_internship/summer20/iqtree/IQ-TREE/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named iqtree

# Build rule for target.
iqtree: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 iqtree
.PHONY : iqtree

# fast build rule for target.
iqtree/fast:
	$(MAKE) -f CMakeFiles/iqtree.dir/build.make CMakeFiles/iqtree.dir/build
.PHONY : iqtree/fast

#=============================================================================
# Target rules for targets named kernelsse

# Build rule for target.
kernelsse: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kernelsse
.PHONY : kernelsse

# fast build rule for target.
kernelsse/fast:
	$(MAKE) -f CMakeFiles/kernelsse.dir/build.make CMakeFiles/kernelsse.dir/build
.PHONY : kernelsse/fast

#=============================================================================
# Target rules for targets named pll

# Build rule for target.
pll: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pll
.PHONY : pll

# fast build rule for target.
pll/fast:
	$(MAKE) -f pll/CMakeFiles/pll.dir/build.make pll/CMakeFiles/pll.dir/build
.PHONY : pll/fast

#=============================================================================
# Target rules for targets named ncl

# Build rule for target.
ncl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ncl
.PHONY : ncl

# fast build rule for target.
ncl/fast:
	$(MAKE) -f ncl/CMakeFiles/ncl.dir/build.make ncl/CMakeFiles/ncl.dir/build
.PHONY : ncl/fast

#=============================================================================
# Target rules for targets named nclextra

# Build rule for target.
nclextra: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nclextra
.PHONY : nclextra

# fast build rule for target.
nclextra/fast:
	$(MAKE) -f nclextra/CMakeFiles/nclextra.dir/build.make nclextra/CMakeFiles/nclextra.dir/build
.PHONY : nclextra/fast

#=============================================================================
# Target rules for targets named utils

# Build rule for target.
utils: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 utils
.PHONY : utils

# fast build rule for target.
utils/fast:
	$(MAKE) -f utils/CMakeFiles/utils.dir/build.make utils/CMakeFiles/utils.dir/build
.PHONY : utils/fast

#=============================================================================
# Target rules for targets named pda

# Build rule for target.
pda: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pda
.PHONY : pda

# fast build rule for target.
pda/fast:
	$(MAKE) -f pda/CMakeFiles/pda.dir/build.make pda/CMakeFiles/pda.dir/build
.PHONY : pda/fast

#=============================================================================
# Target rules for targets named lbfgsb

# Build rule for target.
lbfgsb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lbfgsb
.PHONY : lbfgsb

# fast build rule for target.
lbfgsb/fast:
	$(MAKE) -f lbfgsb/CMakeFiles/lbfgsb.dir/build.make lbfgsb/CMakeFiles/lbfgsb.dir/build
.PHONY : lbfgsb/fast

#=============================================================================
# Target rules for targets named whtest

# Build rule for target.
whtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 whtest
.PHONY : whtest

# fast build rule for target.
whtest/fast:
	$(MAKE) -f whtest/CMakeFiles/whtest.dir/build.make whtest/CMakeFiles/whtest.dir/build
.PHONY : whtest/fast

#=============================================================================
# Target rules for targets named sprng

# Build rule for target.
sprng: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sprng
.PHONY : sprng

# fast build rule for target.
sprng/fast:
	$(MAKE) -f sprng/CMakeFiles/sprng.dir/build.make sprng/CMakeFiles/sprng.dir/build
.PHONY : sprng/fast

#=============================================================================
# Target rules for targets named vectorclass

# Build rule for target.
vectorclass: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vectorclass
.PHONY : vectorclass

# fast build rule for target.
vectorclass/fast:
	$(MAKE) -f vectorclass/CMakeFiles/vectorclass.dir/build.make vectorclass/CMakeFiles/vectorclass.dir/build
.PHONY : vectorclass/fast

#=============================================================================
# Target rules for targets named model

# Build rule for target.
model: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 model
.PHONY : model

# fast build rule for target.
model/fast:
	$(MAKE) -f model/CMakeFiles/model.dir/build.make model/CMakeFiles/model.dir/build
.PHONY : model/fast

#=============================================================================
# Target rules for targets named gsl

# Build rule for target.
gsl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gsl
.PHONY : gsl

# fast build rule for target.
gsl/fast:
	$(MAKE) -f gsl/CMakeFiles/gsl.dir/build.make gsl/CMakeFiles/gsl.dir/build
.PHONY : gsl/fast

#=============================================================================
# Target rules for targets named alignment

# Build rule for target.
alignment: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 alignment
.PHONY : alignment

# fast build rule for target.
alignment/fast:
	$(MAKE) -f alignment/CMakeFiles/alignment.dir/build.make alignment/CMakeFiles/alignment.dir/build
.PHONY : alignment/fast

#=============================================================================
# Target rules for targets named tree

# Build rule for target.
tree: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tree
.PHONY : tree

# fast build rule for target.
tree/fast:
	$(MAKE) -f tree/CMakeFiles/tree.dir/build.make tree/CMakeFiles/tree.dir/build
.PHONY : tree/fast

main/main.o: main/main.cpp.o

.PHONY : main/main.o

# target to build an object file
main/main.cpp.o:
	$(MAKE) -f CMakeFiles/iqtree.dir/build.make CMakeFiles/iqtree.dir/main/main.cpp.o
.PHONY : main/main.cpp.o

main/main.i: main/main.cpp.i

.PHONY : main/main.i

# target to preprocess a source file
main/main.cpp.i:
	$(MAKE) -f CMakeFiles/iqtree.dir/build.make CMakeFiles/iqtree.dir/main/main.cpp.i
.PHONY : main/main.cpp.i

main/main.s: main/main.cpp.s

.PHONY : main/main.s

# target to generate assembly for a file
main/main.cpp.s:
	$(MAKE) -f CMakeFiles/iqtree.dir/build.make CMakeFiles/iqtree.dir/main/main.cpp.s
.PHONY : main/main.cpp.s

main/phyloanalysis.o: main/phyloanalysis.cpp.o

.PHONY : main/phyloanalysis.o

# target to build an object file
main/phyloanalysis.cpp.o:
	$(MAKE) -f CMakeFiles/iqtree.dir/build.make CMakeFiles/iqtree.dir/main/phyloanalysis.cpp.o
.PHONY : main/phyloanalysis.cpp.o

main/phyloanalysis.i: main/phyloanalysis.cpp.i

.PHONY : main/phyloanalysis.i

# target to preprocess a source file
main/phyloanalysis.cpp.i:
	$(MAKE) -f CMakeFiles/iqtree.dir/build.make CMakeFiles/iqtree.dir/main/phyloanalysis.cpp.i
.PHONY : main/phyloanalysis.cpp.i

main/phyloanalysis.s: main/phyloanalysis.cpp.s

.PHONY : main/phyloanalysis.s

# target to generate assembly for a file
main/phyloanalysis.cpp.s:
	$(MAKE) -f CMakeFiles/iqtree.dir/build.make CMakeFiles/iqtree.dir/main/phyloanalysis.cpp.s
.PHONY : main/phyloanalysis.cpp.s

main/phylotesting.o: main/phylotesting.cpp.o

.PHONY : main/phylotesting.o

# target to build an object file
main/phylotesting.cpp.o:
	$(MAKE) -f CMakeFiles/iqtree.dir/build.make CMakeFiles/iqtree.dir/main/phylotesting.cpp.o
.PHONY : main/phylotesting.cpp.o

main/phylotesting.i: main/phylotesting.cpp.i

.PHONY : main/phylotesting.i

# target to preprocess a source file
main/phylotesting.cpp.i:
	$(MAKE) -f CMakeFiles/iqtree.dir/build.make CMakeFiles/iqtree.dir/main/phylotesting.cpp.i
.PHONY : main/phylotesting.cpp.i

main/phylotesting.s: main/phylotesting.cpp.s

.PHONY : main/phylotesting.s

# target to generate assembly for a file
main/phylotesting.cpp.s:
	$(MAKE) -f CMakeFiles/iqtree.dir/build.make CMakeFiles/iqtree.dir/main/phylotesting.cpp.s
.PHONY : main/phylotesting.cpp.s

obsolete/parsmultistate.o: obsolete/parsmultistate.cpp.o

.PHONY : obsolete/parsmultistate.o

# target to build an object file
obsolete/parsmultistate.cpp.o:
	$(MAKE) -f CMakeFiles/iqtree.dir/build.make CMakeFiles/iqtree.dir/obsolete/parsmultistate.cpp.o
.PHONY : obsolete/parsmultistate.cpp.o

obsolete/parsmultistate.i: obsolete/parsmultistate.cpp.i

.PHONY : obsolete/parsmultistate.i

# target to preprocess a source file
obsolete/parsmultistate.cpp.i:
	$(MAKE) -f CMakeFiles/iqtree.dir/build.make CMakeFiles/iqtree.dir/obsolete/parsmultistate.cpp.i
.PHONY : obsolete/parsmultistate.cpp.i

obsolete/parsmultistate.s: obsolete/parsmultistate.cpp.s

.PHONY : obsolete/parsmultistate.s

# target to generate assembly for a file
obsolete/parsmultistate.cpp.s:
	$(MAKE) -f CMakeFiles/iqtree.dir/build.make CMakeFiles/iqtree.dir/obsolete/parsmultistate.cpp.s
.PHONY : obsolete/parsmultistate.cpp.s

tree/phylokernelsse.o: tree/phylokernelsse.cpp.o

.PHONY : tree/phylokernelsse.o

# target to build an object file
tree/phylokernelsse.cpp.o:
	$(MAKE) -f CMakeFiles/kernelsse.dir/build.make CMakeFiles/kernelsse.dir/tree/phylokernelsse.cpp.o
.PHONY : tree/phylokernelsse.cpp.o

tree/phylokernelsse.i: tree/phylokernelsse.cpp.i

.PHONY : tree/phylokernelsse.i

# target to preprocess a source file
tree/phylokernelsse.cpp.i:
	$(MAKE) -f CMakeFiles/kernelsse.dir/build.make CMakeFiles/kernelsse.dir/tree/phylokernelsse.cpp.i
.PHONY : tree/phylokernelsse.cpp.i

tree/phylokernelsse.s: tree/phylokernelsse.cpp.s

.PHONY : tree/phylokernelsse.s

# target to generate assembly for a file
tree/phylokernelsse.cpp.s:
	$(MAKE) -f CMakeFiles/kernelsse.dir/build.make CMakeFiles/kernelsse.dir/tree/phylokernelsse.cpp.s
.PHONY : tree/phylokernelsse.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... package_source"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... iqtree"
	@echo "... package"
	@echo "... kernelsse"
	@echo "... pll"
	@echo "... ncl"
	@echo "... nclextra"
	@echo "... utils"
	@echo "... pda"
	@echo "... lbfgsb"
	@echo "... whtest"
	@echo "... sprng"
	@echo "... vectorclass"
	@echo "... model"
	@echo "... gsl"
	@echo "... alignment"
	@echo "... tree"
	@echo "... main/main.o"
	@echo "... main/main.i"
	@echo "... main/main.s"
	@echo "... main/phyloanalysis.o"
	@echo "... main/phyloanalysis.i"
	@echo "... main/phyloanalysis.s"
	@echo "... main/phylotesting.o"
	@echo "... main/phylotesting.i"
	@echo "... main/phylotesting.s"
	@echo "... obsolete/parsmultistate.o"
	@echo "... obsolete/parsmultistate.i"
	@echo "... obsolete/parsmultistate.s"
	@echo "... tree/phylokernelsse.o"
	@echo "... tree/phylokernelsse.i"
	@echo "... tree/phylokernelsse.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

